# Claves de identificación (Verifica que coincidan con SonarCloud)
sonar.projectKey=api-basic-social
sonar.organization=sbtn63
sonar.projectName=API SOCIAL

# Ubicación del código
sonar.sources=app.js,config,db,libs,middleware,routes,schemas,services
sonar.sourceEncoding=UTF-8

# Configuración de Tests y Cobertura
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
# Es vital añadir la ruta al reporte de LCOV para ver la cobertura real
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusiones (Limpieza de archivos innecesarios)
sonar.exclusions=node_modules/**,**/*.spec.js,**/*.test.js,.github/**,dist/**,build/**,.git/**,coverage/**,Dockerfile,docker-compose.yml,.env*
