sonar.projectKey=api-basic-social
sonar.organization=sbtn63

sonar.host.url=https://sonarcloud.io

sonar.sources=services,db/models/,libs/,config/,app.js
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js

sonar.exclusions=**/node_modules/**,**/test/**,**/db/migrations/**,**/db/seeders/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
