sonar.projectKey=api-social
sonar.projectName=API SOCIAL
sonar.projectVersion=1.0
sonar.sources=app.js,config,db,libs,middleware,routes,schemas,services
sonar.tests=test
sonar.exclusions=node_modules/**,**/*.spec.js,**/*.test.js,.github/**,dist/**,build/**,.git/**,coverage/**,Dockerfile,docker-compose.yml,.env*
sonar.test.inclusions=test/**/*.test.js
sonar.language=js
sonar.sourceEncoding=UTF-8
