name: Node.js CI

on:
  push:
    branches:
      - 'release/*'
  pull_request:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d mysql

      - name: Wait for Mysql
        run: |
          echo "Waiting for Mysql.."
          until docker exec $(docker ps -qf "name=mysql") mysqladmin ping -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} --silent; do
            sleep 1
          done

      - name: Install dependencies
        run: npm install

      - name: Run Eslint
        run: npx eslint .

      - name: Run tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: npm test

      - name: Build application
        run: npm run build

